version: '3'

vars:
  GO_VERSION: '1.24'
  GOLANGCI_LINT_VERSION: 'v2.1.5'
  GCI_VERSION: 'v0.13.6'
  GOFUMPT_VERSION: 'v0.8.0'
  OGEN_VERSION: 'v1.14.0'
  YQ_VERSION: 'v4.45.2'
  BUF_VERSION: '1.53.0'
  PROTOC_GEN_GO_VERSION: 'v1.36.6'
  PROTOC_GEN_GO_GRPC_VERSION: 'v1.5.1'
  PROTOC_GEN_GRPC_GATEWAY_VERSION: 'v2.26.3'
  PROTOC_GEN_VALIDATE_VERSION: 'v1.2.1'
  PROTOC_GEN_OPENAPIV2_VERSION: 'v2.26.3'

  BIN_DIR: '{{.USER_WORKING_DIR}}/bin'
  GOLANGCI_LINT: '{{.BIN_DIR}}/golangci-lint'
  GCI: '{{.BIN_DIR}}/gci'
  GOFUMPT: '{{.BIN_DIR}}/gofumpt'
  OGEN: '{{.BIN_DIR}}/ogen'
  YQ: '{{.BIN_DIR}}/yq'


  REDOCLY: 'npx --no-install redocly'


  OPEN_API_ORDER_V1_BASE: './shared/api/order/v1/order.openapi.yaml'
  OPEN_API_ORDER_V1_BUNDLE: './shared/api/bundles/order/order.openapi.v1.bundle.yaml'
  OPEN_API_FILES: './shared/api/bundles/order'
  BUF: '{{.BIN_DIR}}/buf'
  PROTOC_GEN_GO: '{{.BIN_DIR}}/protoc-gen-go'
  PROTOC_GEN_GO_GRPC: '{{.BIN_DIR}}/protoc-gen-go-grpc'
  PROTOC_GEN_GRPC_GATEWAY: '{{.BIN_DIR}}/protoc-gen-grpc-gateway'
  PROTOC_GEN_VALIDATE: '{{.BIN_DIR}}/protoc-gen-validate'
  PROTOC_GEN_OPENAPIV2: '{{.BIN_DIR}}/protoc-gen-openapiv2'


tasks:
  install-formatters:
    desc: "Устанавливает форматтеры gci и gofumpt в ./bin"
    cmds:
      - |
        [ -f {{.GOFUMPT}} ] || {
          echo '📦 Устанавливаем gofumpt {{.GOFUMPT_VERSION}}...'
          GOBIN={{.BIN_DIR}} go install mvdan.cc/gofumpt@{{.GOFUMPT_VERSION}}
        }
        [ -f {{.GCI}} ] || {
          echo '📦 Устанавливаем gci {{.GCI_VERSION}}...'
          GOBIN={{.BIN_DIR}} go install github.com/daixiang0/gci@{{.GCI_VERSION}}
        }
    status:
      - test -x {{.GOFUMPT}}
      - test -x {{.GCI}}

  format:
    desc: "Форматирует весь проект gofumpt + gci"
    deps: [ install-formatters ]
    cmds:
      - echo "🧼 Форматируем через gofumpt ..."
      # Просто указываем ".", gofumpt сам найдет все .go файлы рекурсивно
      - '"{{.GOFUMPT}}" -extra -w .'
      - echo "🎯 Сортируем импорты через gci ..."
      # gci тоже умеет рекурсивно обходить директории
      - '"{{.GCI}}" write -s standard -s default -s "prefix(github.com/olezhek28/microservices-course-examples/)" .'

  install-golangci-lint:
    desc: "Устанавливает golangci-lint в каталог bin"
    cmds:
      - |
        [ -f {{.GOLANGCI_LINT}} ] || {
          mkdir -p {{.BIN_DIR}}
          echo "📦 Устанавливаем golangci-lint {{.GOLANGCI_LINT_VERSION}}..."
          GOBIN={{.BIN_DIR}} go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@{{.GOLANGCI_LINT_VERSION}}
        }
    status:
      - test -x {{.GOLANGCI_LINT}}

  lint:
    desc: "Запускает golangci-lint для всех модулей"
    deps: [ install-golangci-lint ]
    cmds:
      - |
        for dir in inventory-service order-service payment-service shared; do
          echo "Линтинг $dir..."
          (cd "$dir" && "{{.GOLANGCI_LINT}}" run ./... --config="../.golangci.yml")
        done

  redocly-cli:install:
    desc: Установить локально Redocly CLI
    cmds:
      - |
        if [ ! -d "node_modules" ]; then
          npm install
        fi

  redocly-cli:order-v1-bundle:
    desc: Собрать OpenAPI в один файл через локальный redocly
    deps: [ redocly-cli:install ]
    cmds:
      - '{{.REDOCLY}} bundle {{.OPEN_API_ORDER_V1_BASE}} -o {{.OPEN_API_ORDER_V1_BUNDLE}}'

  redocly-cli:bundle:
    desc: Собрать все схемы OpenAPI в общие файлы через локальный redocly
    deps: [ redocly-cli:install ]
    cmds:
      - task: redocly-cli:order-v1-bundle

  ogen:install:
    desc: "Скачивает ogen в папку bin"
    cmds:
      - |
        [ -f {{.OGEN}} ] || {
          mkdir -p {{.BIN_DIR}}
          GOBIN={{.BIN_DIR}} go install github.com/ogen-go/ogen/cmd/ogen@{{.OGEN_VERSION}}
        }

  ogen:gen:
    desc: "Генерация Go-кода из всех OpenAPI-деклараций с x-ogen"
    deps: [ ogen:install, yq:install ]
    cmds:
      - task: redocly-cli:bundle
      # Вместо find используем стандартный glob bash (если запускаешь в Git Bash)
      # Если файлов немного, можно просто перечислить или упростить цикл
      - |
        for file in {{.OPEN_API_FILES}}/*.{yaml,yml}; do
          [ -e "$file" ] || continue
          if grep -q 'x-ogen:' "$file"; then
            echo "🚀 Generating from: $file"
            target=$("{{.YQ}}" e '."x-ogen".target' "$file")
            package=$("{{.YQ}}" e '."x-ogen".package' "$file")
            "{{.OGEN}}" --target "$target" --package "$package" --clean "$file" || exit 1
          fi
        done

  yq:install:
    desc: "Устанавливает yq в bin/ при необходимости"
    cmds:
      - |
        [ -f {{.YQ}} ] || {
          echo '📦 Installing yq...'
          GOBIN={{.BIN_DIR}} go install github.com/mikefarah/yq/v4@{{.YQ_VERSION}}
        }
  

  install-buf:
    desc: "Устанавливает Buf в каталог bin"
    cmds:
      - |
        mkdir -p {{.BIN_DIR}}
        [ -f {{.BUF}} ] || {
          echo '📦 Устанавливаем buf {{.BUF_VERSION}}...'
          GOBIN={{.BIN_DIR}} go install github.com/bufbuild/buf/cmd/buf@v{{.BUF_VERSION}}
        }
    status:
      - test -x {{.BUF}}

  proto:install-plugins:
    desc: "Устанавливает protoc плагины в каталог bin"
    cmds:
      - |
        [ -f {{.PROTOC_GEN_GO}} ] || {
          echo '📦 Installing protoc-gen-go...'
          GOBIN={{.BIN_DIR}} go install google.golang.org/protobuf/cmd/protoc-gen-go@{{.PROTOC_GEN_GO_VERSION}}
        }
        [ -f {{.PROTOC_GEN_GO_GRPC}} ] || {
          echo '📦 Installing protoc-gen-go-grpc...'
          GOBIN={{.BIN_DIR}} go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@{{.PROTOC_GEN_GO_GRPC_VERSION}}
        }
        [ -f {{.PROTOC_GEN_GRPC_GATEWAY}} ] || {
          echo '📦 Installing protoc-gen-grpc-gateway...'
          GOBIN={{.BIN_DIR}} go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway@{{.PROTOC_GEN_GRPC_GATEWAY_VERSION}}
        }
        [ -f {{.PROTOC_GEN_VALIDATE}} ] || {
          echo '📦 Installing protoc-gen-validate...'
          GOBIN={{.BIN_DIR}} go install github.com/envoyproxy/protoc-gen-validate@{{.PROTOC_GEN_VALIDATE_VERSION}}
        }
        [ -f {{.PROTOC_GEN_OPENAPIV2}} ] || {
          echo '📦 Installing protoc-gen-openapiv2...'
          GOBIN={{.BIN_DIR}} go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2@{{.PROTOC_GEN_OPENAPIV2_VERSION}}
        }
  proto:gen-openapi:
    desc: "Генерация OpenAPI для inventory и payment"
    deps: [ install-buf, proto:install-plugins ]
    dir: shared/proto
    cmds:
      - '"{{.BUF}}" generate --template buf.gen.inventory.yaml --path ./inventory/v1'
      - '"{{.BUF}}" generate --template buf.gen.payment.yaml --path ./payment/v1'
  proto:update-deps:
    deps: [ install-buf ]
    desc: Обновляет зависимости protobuf из удаленных репозиториев (googleapis и т.д.)
    dir: shared/proto
    cmds:
      - '"{{.BUF}}" dep update'

  proto:lint:
    deps: [ install-buf, proto:install-plugins, proto:update-deps ]
    desc: Проверка .proto-файлов на соответствие стилю
    dir: shared/proto
    cmds:
      - '"{{.BUF}}" lint'

  proto:gen:
    deps: [ install-buf, proto:install-plugins, proto:lint ]
    desc: Генерация Go-кода из .proto
    dir: shared/proto
    cmds:
      - '"{{.BUF}}" generate'

