openapi: 3.0.3
info:
  title: OrderService API
  version: 1.0.0
  description: API for Order Service
x-ogen:
  target: ./shared/pkg/openapi/order/v1
  package: order_v1
  clean: true

tags:
  - name: Order
    description: Endpoints for work with order service
paths:
  /api/v1/orders:
    $ref: ./paths/orders.yaml
  /api/v1/orders/{uuid}:
    $ref: "./paths/order_by_uuid.yaml"
  /api/v1/orders/{uuid}/cancel:
    $ref: "./paths/order_cancel.yaml"
  /api/v1/orders/{uuid}/pay:
    $ref: "./paths/order_pay.yaml"



